### ISSUE TITLE
Feature request: Make dropdown list layout like the default select form

### ISSUE THREAD

**Issue by LutzFassl** [RobertoFN/streamlit-datalist#1]
Great component - thank you :-)

Two feature request I would have:

## 1. Adjust the layout so it follows the standard streamlit design. See comparison with select box:
**Select Box:**
![image](https://user-images.githubusercontent.com/37546799/218075413-6cec1da0-7842-4e66-8419-d24f1c7515f0.png)

**Streamlit-Datalist:**
![image](https://user-images.githubusercontent.com/37546799/218075265-451fb8ed-04df-408f-b93f-d726348c2713.png)

## 2. Add "disabled" argument
 (no further description required)

## 3. Allow the streamlit formatting of the label string (e.g. **bold**, ":red[this text is red]", etc.)**
 (no further description required)

**Comment by RobertoFN** [comment]
`Disabled` feature added in PR #4. Will update when feature is released in pypi.

**Comment by RobertoFN** [comment]
I'll create new issues to individually track these requests.
- [ ] Change UI to look like Streamlit select boxes.
- [ ] Allow Markdown formatting of widget title.

**Comment by RobertoFN** [comment]
`Disabled` feature released in [v0.0.5](https://pypi.org/project/streamlit-datalist/0.0.5/)

Splitting the other 2 requests into their own issues (#6 , #7)

**Comment by RobertoFN** [comment]
Also, the issue with caching/showing list of values from other datalists should be fixed in the latest release as well. 
Implemented a fix and it seemed to work fine, but do feel free to open another issue if the problem still persists.

**Comment by LutzFassl** [comment]
Awesome! I can confirm it only shows the correct options now - thanks a lot Roberto!
