### ISSUE TITLE
Sidebar Support?

### ISSUE THREAD

**Issue by BSalita** [RobertoFN/streamlit-datalist#2]
Thanks for contributing this helpful component. When I attempt to use with sidebar `st.sidebar.Datalist`, I get an exception `stDatalist()` is not a valid Streamlit command. Is sidebar supported in some way?

**Comment by RobertoFN** [comment]
Hi. You can add components to the sidebar by using `with`, discussed in this Streamlit Forum [discussion](https://discuss.streamlit.io/t/is-it-possible-to-create-a-custom-component-and-include-it-inside-the-sidebar/4595) and this [blogpost entry](https://blog.streamlit.io/introducing-new-layout-options-for-streamlit/).

Just tried it and it should work by writing:
```
with st.sidebar:
    value = stDatalist('Title', data)
```

Hope that helps!
